### ISSUE TITLE
Toggle for all layers in a group

### ISSUE THREAD

**Issue by kingrollo** [jjimenezshaw/Leaflet.Control.Layers.Tree#2]
Hello.

Is there a way of toggling all the layers in a layer group at once?

Thanks!
R.

**Comment by jjimenezshaw** [comment]
@kingrollo this feature is not implemented itself. Maybe you can do some hack in your code detecting the changes in the layers. But it is not directly in the tree.
You can implement a pull request to include that :)
Unfortunately I do not have time now :'(

If you want to enable many layers at once, of course you can make a group layer. However, you shouldn't include both in the tree, the group and the layer alone. It has estrange behaviors: there can be contradictions (i.e. the group is disabled, but one element is enabled. Which one rules?)

**Comment by jjimenezshaw** [comment]
Some time ago I added a new functionality to select all the layers in a group. Maybe it is useful for you, @kingrollo
