### ISSUE TITLE
There is any possibility to implement an opacity slider control for each layer?

### ISSUE THREAD

**Issue by aapopei** [jjimenezshaw/Leaflet.Control.Layers.Tree#21]
Does the code support opacity control for each layer from the tree? How can achieve this? I suppose that you need to put an input slider on each active layer, right?

**Comment by jjimenezshaw** [comment]
Something like this?
https://next.plnkr.co/edit/54ixRjHhdz5HBr2T

**Comment by aapopei** [comment]
Thank you for your time and knowledge, works fine on mobile devices, especially the UI input sliders.

**Comment by MickGe** [comment]
Thank you very **much** !
You help me to add dblclick in overlay to fly to marker.
[Link here to my codesandbox](https://codesandbox.io/s/leaflet-control-tree-flyto-ondblclick-in-overlay-g6dew) if it can help others like me. 😉
