### ISSUE TITLE
sortLayers:true is not working

### ISSUE THREAD

**Issue by nrtkrishna** [jjimenezshaw/Leaflet.Control.Layers.Tree#24]
I gave sortLayers:true option but the tree layers or groups are not sorted.

**Comment by jjimenezshaw** [comment]
Due to tree construction (the tree cannot be modified, nodes added, etc), `sortLayers` does not work. You have to implement that before creating it. I will document it in the next release.

**Comment by nrtkrishna** [comment]
ok..thank you. That would be great. For now can I proceed with sorting array and passing it to overlays?

**Comment by jjimenezshaw** [comment]
Yes. Sort it in the object you pass before you create the tree.
