### ISSUE TITLE
Icons/ Symbols for each Overlay's children

### ISSUE THREAD

**Issue by Dinuxax100** [jjimenezshaw/Leaflet.Control.Layers.Tree#25]
Hi,

Thanks for the Control.Layers.Tree.

I am new to Leaflet. In the Control.Layers.Tree, is it possible to add the Icons/ Symbols for each Overlay's children? I need different Symbols will define for each Overlay's childer layer.

**Comment by jjimenezshaw** [comment]
The `label` is a valid HTML string. You can add there any valid HTML, including fontawsome icons, images, or whatever you want.
