### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by katagen** [jjimenezshaw/Leaflet.Control.Layers.Tree#27]
Hi,
When I try your exemple, it seems that there is a problem with the rendering...
![Capture d’écran 2020-06-15 à 23 47 12](https://user-images.githubusercontent.com/37768582/84709578-b796f180-af62-11ea-821a-b2866602e64f.png)

I have the same problem if I try on my data...

Any idee?

**Comment by jjimenezshaw** [comment]
Have you linked `L.Control.Layers.Tree.css` in the html?

Something like
`<link rel="stylesheet" href="../L.Control.Layers.Tree.css">`

**Comment by katagen** [comment]
Hi,
I think so...
If I use your exemple named "basic.html", I have this:

[basic.zip](https://github.com/jjimenezshaw/Leaflet.Control.Layers.Tree/files/4785428/basic.zip)


The structure is like that:
![image](https://user-images.githubusercontent.com/37768582/84751261-a7136500-afbc-11ea-8446-6d20d133977b.png)
 As you can see, the HTML file is at the same place as the JS and CSS files.
But the result is wrong:
![Sans titre](https://user-images.githubusercontent.com/37768582/84752226-c2cb3b00-afbd-11ea-920d-108d281cc0e7.png)

**Comment by jjimenezshaw** [comment]
remove `crossorigin=""`

There is an error in the console:

`Access to CSS stylesheet at 'file:///home/.../L.Control.Layers.Tree.css' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

**Comment by katagen** [comment]
Super, it works now... Thank you!
