### ISSUE TITLE
Exclusive Group Layers

### ISSUE THREAD

**Issue by mpbotti** [jjimenezshaw/Leaflet.Control.Layers.Tree#4]
Hi Javier! I am making the last adjustments to my map and I realized that your tool does not allow define a group of exclusive layers that can be selected one at a time (as the basemaps does...). I have a bunch of layers with wind forecast every three hours and I want to select only one each time. Could you please include this functionality in next releases? Many thanks for your time, M.

**Comment by jjimenezshaw** [comment]
I guess you mean the `radioGroup` attribute (already explained at the [end of the readme](https://github.com/jjimenezshaw/Leaflet.Control.Layers.Tree#tricks-about-the-tree))

**Comment by mpbotti** [comment]
Yes I saw it, and tried to make it works, but I cant do it... yet!
I keep trying though...
Thanks...

**Comment by jjimenezshaw** [comment]
Look at this example https://jjimenezshaw.github.io/Leaflet.Control.Layers.Tree/examples/options.html

**Comment by mpbotti** [comment]
Damn! The only one thing I did not try...
Thank you!
