### ISSUE TITLE
Legend Control

### ISSUE THREAD

**Issue by mmirhi** [jjimenezshaw/Leaflet.Control.Layers.Tree#6]
Hi 

Thank you for the great function. 

When you say: "addBaseLayer, addOverlay and removeLayer are non usable in L.Control.Layers.Tree.", do you mean I cannot control the legends of the map for each layer?

Thank you

**Comment by jjimenezshaw** [comment]
Hi.
Sorry for the late answer. For some reason I didn't get any notification.

Those methods are not usable because they add (or remove) a layer incrementally, at the end of the list. Due to the tree structure, you have to provide the full tree, not layers one by one.
