### ISSUE TITLE
How to change the title (hint text) of toggle button? 

### ISSUE THREAD

**Issue by carlshe** [jjimenezshaw/Leaflet.Control.Layers.Tree#63]
For different language, how to set the title (hint text) of toggle button?  Thanks!

**Comment by jjimenezshaw** [comment]
Which toggle button do you mean exactly? If it is the control itself, it behaves like [Control.Layers](https://leafletjs.com/reference.html#control-layers). For anything inside the tree, you can use standard HTML.

**Comment by carlshe** [comment]
Thank you very much! Yes. What I mean is the the toggle button itself.
I found the code in Control.Layers. It is not public. So I had to set it by modifying the code.
