### ISSUE TITLE
How to reference DOM label selector in tree [upon selection]

### ISSUE THREAD

**Issue by cspence001** [jjimenezshaw/Leaflet.Control.Layers.Tree#64]
Is there a way to have the tree selection reference an object request? Right now I have an HTML selection that first requests a json  file through an click() event in javascript that parses the data to create circle markers with attributes sorted into layerGroups that are filtered through an overlay layer control module upon selection from the tree. 

What I would like to do is instead trigger the request for the object when it is selected through the tree to then subsequently parse the data in the function that creates the circle markers and sorts them into layerGroups.

**Comment by jjimenezshaw** [comment]
Sorry @cspence001 I do not understand what you want to do. Could  you explain it in a different way? Simple samples are always useful.

**Comment by cspence001** [comment]
So I have my layer tree:
                {
                  label: 'State',
                  collapsed: true,
                  selectAllCheckbox: true,
                  children: [
                      { label: 'IL', layer: ILgroup },
                      { label: 'MD', layer: MDgroup },
                      { label: 'VA', layer: VAgroup },
                  ]},
                       { label: IND',
                        selectAllCheckbox: true,
                        collapsed: true,
                        children: [
                          { label: '0000', layer: ind11ss11group },
                          { label: '1111', layer: ind11ss12group },
                          { label: '1112', layer: ind11ss13group }
                          ]},
                       {
	                    label: '<b>JR</b>',
	                    collapsed: true,
	                    selectAllCheckbox: true,
	                    children: [
	                        { label: 'Fewer than 5', layer: JR1group},
	                        { label: '5 to 9', layer: JR2group},
	                        { label: '10 to 19', layer: JR3group }
	                        ]}


Layer Filter Control:
      const content = L.layerGroup().addTo(myMap);
        // filter selection
        myMap.on('overlayadd overlayremove', () => {
       if (myMap.hasLayer(ind00ss00group)) { objSS['IND00SS00'].forEach(marker=> marker.addTo(content))
        }
       if (myMap.hasLayer(ind11ss11group)) { objSS['IND11SS11'].forEach(marker=> marker.addTo(content))
        }
       if (myMap.hasLayer(ind11ss12group)) { objSS['IND11SS12'].forEach(marker=> marker.addTo(content))
        }

          if (!myMap.hasLayer(JR1group)) {
              objJR['JR1'].forEach(marker => content.removeLayer(marker))
          }
          if (!myMap.hasLayer(JR2group)) {
              objJR['JR2'].forEach(marker => content.removeLayer(marker))
          }


My layer group objects:
let ind00ss00group = new L.layerGroup();
let ind11ss11group = new L.layerGroup();
let ind11ss12group = new L.layerGroup();

let JR1group = new L.layerGroup();
let JR2group = new L.layerGroup();

Lists containing object markers for each group (after loaded in request below):
let objSS = {
'IND00SS00': [],
'IND11SS11': [],
'IND11SS12': []
}
let objJR = {
'JR1': [],
'JR2': []
}

This button is connected to a separate request module where the data is loaded (based on a state selection) and the function parses the markers to push into the object lists.  The tree selections will only show data that has been previously requested : 

  $("#mybutton5").click(function (event) { 
  if ($("input[name='points']:checked")){
    ptsData = $("input[name='points']:checked").val()
    var idVal = $("input[name='points']:checked").attr('id')
    var d1 = $(`#label[for='${idVal}']`)
  }
  const fipssubGroups = new L.layerGroup();

  const subGroups = [];
  industry = L.geoJson.ajax(ptsData, {
    pointToLayer: function (feature){
        return new L.circleMarker([feature.geometry.coordinates[1], feature.geometry.coordinates[0]], {
        className: feature.properties.HASHcodePM,
        radius: getRadius(feature.properties.Amount),
        fillOpacity:0.8,
        color: getColor(feature.properties.Industry),
        fillColor: getColor(feature.properties.Industry),
        weight: getRadius(feature.properties.Amount)/3,
    }) //ends circleMarker
  }, //end pointToLayer
    onEachFeature: function(feature, layer) {
      layer.bindPopup("<b>Recipient</b>: " + feature.properties.Name)
      var HASHcode = feature.properties["HASHcodePM"];
      var INDSShash = feature.properties.HASHcodePM.slice(0,9);  
      var JRhash = feature.properties.HASHcodePM.slice(12,15); 

      var tagCategories = subGroups[HASHcode];
      if (!tagCategories) {
        tagCategories = subGroups[HASHcode] = L.geoJson();
        //tagCategories._leaflet_id = HASHcode; //renames layer 
      } tagCategories.addLayer(layer); //tagCategories.addTo(mainTag)

	  objSS[INDSShash].push(tagCategories)
      objJR[JRhash].push(tagCategories);

    }, //ends onEachFeature
  }) //ends ajax request
}); //ends click function 


What I want to do is have this button reference the selection in the tree rather than use a separate HTML form (python API module completing request.) So is there a way I can reference the label selected in the tree?

**Comment by cspence001** [comment]
nice updates
