### ISSUE TITLE
Adding Icons to Layers

### ISSUE THREAD

**Issue by cmwright93** [jjimenezshaw/Leaflet.Control.Layers.Tree#7]
Hello,

I noticed there is an icon of the continents being used in the initial example, but no demonstration for how to implement the use of icons in the layers tree. Any code examples on how to incorporate icons in next to the layers? Thanks.

**Comment by jjimenezshaw** [comment]
Hi
Sorry for the late answer. For some reason I didn't get any notification.

In the examples I used Unicode chars as regular HTML text. Probably to refer to this:
https://emojipedia.org/world-map/ https://unicode-table.com/en/1F5FA/
&#x1F5FA; `&#x1F5FA;`

Be careful. Not every browser supports all of them. https://fontawesome.com is another option.
