### ISSUE TITLE
the tree doe not work correctly can you help me

### ISSUE THREAD

**Issue by TmCoop** [jjimenezshaw/Leaflet.Control.Layers.Tree#75]
![image](https://github.com/user-attachments/assets/d8d0ec73-dab7-4821-9342-935ad527ec15)

Aas you can see in the image i cant open or collapse the tree nodes.
has anybody an Idea what the reason can be and how i can fix it?

**Comment by jjimenezshaw** [comment]
Are you including the css properly?

**Comment by TmCoop** [comment]
i have used npm install

**Comment by TmCoop** [comment]
no it works
